package foo;

import org.assertj.core.api.AbstractAssert;
import org.assertj.core.util.Objects;

/**
 * {@link Hoge} specific assertions - Generated by CustomAssertionGenerator.
 */
public class HogeAssert extends AbstractAssert<HogeAssert, Hoge> {

  /**
   * Creates a new <code>{@link HogeAssert}</code> to make assertions on actual Hoge.
   * @param actual the Hoge we want to make assertions on.
   */
  public HogeAssert(Hoge actual) {
    super(actual, HogeAssert.class);
  }

  /**
   * An entry point for HogeAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myHoge)</code> and get specific assertion with code completion.
   * @param actual the Hoge we want to make assertions on.
   * @return a new <code>{@link HogeAssert}</code>
   */
  public static HogeAssert assertThat(Hoge actual) {
    return new HogeAssert(actual);
  }

  /**
   * Verifies that the actual Hoge's age is equal to the given one.
   * @param age the given age to compare the actual Hoge's age to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Hoge's age is not equal to the given one.
   */
  public HogeAssert hasAge(int age) {
    // check that actual Hoge we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting age of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // check
    int actualAge = actual.getAge();
    if (actualAge != age) {
      failWithMessage(assertjErrorMessage, actual, age, actualAge);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual Hoge's name is equal to the given one.
   * @param name the given name to compare the actual Hoge's name to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Hoge's name is not equal to the given one.
   */
  public HogeAssert hasName(String name) {
    // check that actual Hoge we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting name of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualName = actual.getName();
    if (!Objects.areEqual(actualName, name)) {
      failWithMessage(assertjErrorMessage, actual, name, actualName);
    }

    // return the current assertion for method chaining
    return this;
  }

}
